# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dan Bauman

# This is the place to set up the contact form recipient
# email: your-email@example.com

description: Gumshoe. Analyst. Force Multiplier.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
bluesky_username: danbauman77.bsky.social
github_username:  danbauman77

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-admin
  - jekyll-gist
  - jekyll-seo-tag

sass:
  load_paths:
    - bower_components/

incremental: true

exclude: ['gulpfile.js', 'Gemfile', 'Gemfile.lock']

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

defaults:
  - scope:
      path: "/portfolio"
      type: portfolio
    values:
      layout: portfolio

# This is the place to set up the commenting system
# disqus:
#   shortname: your-disqus-shortname

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

gated_content:
  enabled: true
  default_excerpt_length: 300
  gated_pages:
    - eyeing-retirement-boomers-ready-for-health-care-costs
  ungated_pages:
    - how-the-u-of-arizona-found-itself-in-a-financial-crisis-of-its-own-making
    - targets-travails-in-7-charts
    - 2-states-restricted-dei-heres-how-colleges-revised-their-websites
    - 39-private-college-leaders-earn-more-than-1-million
    - 43-years-20-properties-a-look-at-webster-universitys-residential-properties-in-webster-groves
    - a-glimpse-at-the-connections-among-7-debt-relief-companies
    - a-new-mega-university-expects-to-earn-big-money-immediately-are-its-projections-too-ambitious
    - a-pandemic-era-cut-with-a-hidden-price-tag
    - a-university-had-big-goals-for-expansion-now-its-drastically-cutting-back
    - a-watchdog-admonished-the-education-dept-for-not-monitoring-loan-servicers-here-are-3-takeaways-from-that-report
    - accreditor-ratchets-up-pressure-on-north-idaho-college-with-show-cause-order
    - after-2016-election-campus-hate-crimes-seemed-to-jump-heres-what-the-data-tell-us
    - after-a-2-year-courtship-the-u-of-idaho-calls-off-pursuit-of-the-u-of-phoenix
    - after-final-warning-from-its-accreditor-north-idaho-colleges-credit-rating-is-downgraded
    - americas-standardized-testing-giants-are-losing-money-fast
    - amid-financial-headwinds-some-colleges-are-digging-deeper-into-their-endowments-will-more-follow
    - amid-volatility-and-uncertainty-should-colleges-spend-down-their-surpluses
    - arizona-state-u-is-expanding-to-california-its-been-rocky
    - as-coronavirus-drives-students-from-campuses-what-happens-to-the-workers-who-feed-them
    - auditors-reviewed-how-uvas-police-prepared-for-white-supremacists-they-didnt-like-what-they-found
    - bill-would-bar-sex-offenders-from-living-near-parks-or-almost-anywhere-in-the-twin-cities
    - billions-of-dollars-are-at-stake-under-trumps-funding-freeze-what-could-that-mean-for-your-college
    - bonuses-push-more-public-college-leaders-past-1-million
    - can-these-degree-programs-under-assault-for-a-decade-survive-a-pandemic
    - college-without-credit-former-student-attends-class-with-pending-default-on-student-debt
    - colleges-were-already-bracing-for-an-enrollment-cliff-now-there-might-be-a-second-one
    - columbias-interim-president-steps-down-board-co-chair-named-as-replacement
    - congress-should-scrutinize-higher-eds-use-of-predictive-analytics-watchdog-says
    - congressional-republicans-want-to-end-grad-plus-loans-how-might-it-affect-your-campus
    - consultants-see-demand-rise-as-aca-is-installed
    - coronavirus-has-choked-off-revenues-for-private-colleges-how-much-cash-do-they-have-on-hand
    - could-north-idaho-college-really-lose-its-accreditation
    - despite-sky-high-inflation-no-sign-yet-of-surging-tuition-costs
    - do-graduate-assistants-earn-a-living-wage-not-in-these-cities
    - does-it-matter-if-a-political-candidate-has-steep-student-loan-debts-georgians-will-get-to-decide
    - drew-cloud-is-a-well-known-expert-on-student-loans-one-problem-hes-not-real
    - education-dept-alleges-years-of-safety-failures-by-liberty-u
    - education-dept-to-end-funding-for-minority-serving-institutions-affecting-hundreds-of-colleges
    - education-dept-warns-college-operator-not-to-mislead-students-as-its-campuses-close
    - executive-compensation-at-public-colleges-rises-by-5-with-texas-leading-the-way
    - expect-defaults-to-surge-when-student-loan-repayments-resume-warns-n-y-fed
    - faculty-students-give-input-on-chess-programs-past-future
    - following-colleagues-comments-on-racism-jama-editors-resignation-came-with-500-000-payout
    - hate-crimes-on-campuses-are-rising-new-fbi-data-show
    - here-are-the-hottest-college-sports-and-the-ones-in-decline
    - heres-what-we-know-about-private-college-police-departments
    - heres-who-was-hit-hardest-by-higher-eds-pandemic-driven-job-losses
    - how-a-10-million-accounting-error-rattled-the-u-of-hartford
    - how-a-defense-dept-program-equips-campus-police-forces
    - how-a-for-profit-tycoon-turned-his-colleges-into-nonprofits
    - how-a-president-decided-it-was-time-to-close-his-college
    - how-americas-college-closure-crisis-leaves-families-devastated
    - how-chasing-prestige-is-starting-to-strain-some-elite-institutions
    - how-many-minnesota-police-encounters-turn-fatal-dont-ask-the-state
    - how-more-than-200-scholars-reached-the-provosts-office-and-where-they-went-next
    - how-russian-trolls-used-higher-ed-to-sow-discord-online
    - how-scandal-and-severance-enrich-private-college-presidents
    - how-the-ncaas-march-madness-windfall-makes-its-way-to-colleges
    - how-the-u-of-chicagos-financial-strains-are-a-warning-for-higher-ed
    - i-called-4-companies-for-advice-on-my-student-debt-this-is-what-i-learned
    - in-its-latest-public-filings-liberty-u-blasts-the-president-who-turned-it-into-a-billion-dollar-behemoth
    - inside-the-process-that-jump-starts-federal-sex-harassment-lawsuits
    - inside-wright-states-6-year-journey-into-financial-trouble
    - is-student-debt-big-enough-to-hold-back-the-economy-what-the-research-says
    - leap-from-legislator-to-lobbyist-a-short-one-in-minnesota
    - michigan-state-just-agreed-to-pay-500-million-to-settle-sexual-abuse-claims-where-will-it-find-the-money
    - moving-the-goalposts-what-you-need-to-know-about-devoss-closer-scrutiny-of-foreign-gifts
    - new-tax-law-takes-aim-at-higher-educations-millionaires-club
    - on-campus-grenade-launchers-m-16s-and-armored-vehicles
    - on-election-day-heres-what-higher-ed-should-watch-for
    - one-million-dollar-chess-program-proposal-made-by-susan-polgar-to-texas-tech-documents-reveal
    - one-public-college-president-made-4-million-last-year-now-his-university-wants-it-back
    - players-leverage-their-chess-skills-to-earn-us-college-education
    - police-shooting-in-minnesota-2004-present
    - presidential-tenures-are-getting-shorter-why-are-the-payouts-so-large
    - private-college-presidents-reap-millions-from-long-tenures
    - private-colleges-had-58-millionaire-presidents-in-2015
    - promises-of-debt-relief-meet-privacy-concerns
    - public-regional-colleges-were-already-struggling-covid-19-may-push-some-to-the-brink
    - report-faults-education-dept-s-oversight-of-debt-collection-firms-it-hires
    - should-the-education-dept-start-collecting-its-own-debts
    - some-colleges-pay-for-space-on-a-classic-game-board-it-aint-monopoly-money
    - some-colleges-push-students-to-delay-loan-repayments-theyll-pay-more-in-interest-later
    - sometimes-perceptions-of-affirmative-action-dont-mesh-with-reality
    - st-paul-paid-out-10-4-million-in-staff-overtime-in-2014
    - t-shirts-conferences-and-rising-salaries-heres-whats-in-turning-point-usas-latest-financial-disclosure
    - thanks-to-outreach-u-s-colleges-enjoy-jump-in-gifts-from-abroad
    - the-college-that-drowned-itself-in-red-ink
    - the-cost-of-college-tuition-is-shrinking
    - the-feds-want-to-cement-change-at-columbia-with-a-consent-decree-heres-how-that-would-work
    - the-foundation-at-the-center-of-the-admissions-bribery-scandal-has-a-surprising-item-in-its-portfolio-the-versatile-ph-d
    - the-pitch-debt-relief-the-reality-borrowers-may-pay-more
    - the-worst-case-scenario-what-financial-disclosures-tell-us-about-coronaviruss-strain-on-colleges-so-far
    - these-colleges-cut-back-during-the-pandemic-except-when-it-came-to-their-presidents-pay-packages
    - these-minority-serving-institutions-could-lose-money-under-the-house-republicans-new-plan
    - trump-administration-turns-up-heat-on-harvard-with-financial-lever
    - trump-plans-to-shutter-usaid-heres-what-that-could-mean-for-higher-ed
    - trump-wants-to-cut-billions-in-research-spending-heres-how-much-it-might-cost-your-university
    - trumps-threat-to-cut-federal-funding-to-harvard-by-the-numbers
    - two-years-after-promising-a-transformational-partnership-the-u-of-arizona-and-zovio-part-ways
    - ucf-may-pay-its-former-president-to-leave-heres-how-that-deal-stacks-up-against-others-like-it
    - university-houses-and-perks-not-just-for-presidents
    - update-captured-gaddafi-son-shares-a-past-linked-to-webster-university
    - usc-paid-former-medical-school-dean-accused-of-drug-fueled-double-life-nearly-1-million-in-severance
    - welcome-students-need-a-checking-account
    - were-tracking-confederate-monuments-tell-us-whats-on-your-campus
    - what-4-billionaires-with-russia-ties-have-donated-to-american-colleges
    - when-private-colleges-cut-ties-with-presidents-it-can-mean-a-6-figure-golden-parachute
    - who-foots-most-of-the-bill-for-public-colleges-in-28-states-its-students
    - who-owns-downtown-st-paul
    - who-the-board-of-trustees-donated-to-for-the-2011-2012-election-cycle
    - whose-brilliant-idea-was-this-how-ohio-state-successfully-trademarked-the-word-the
    - why-is-west-virginia-u-making-sweeping-cuts
    - why-students-are-leaving-illinois-in-droves-and-why-it-matters
    - will-your-college-get-any-money-from-the-last-round-of-u-s-covid-relief-check-our-list
    - work-in-public-education-and-hate-chegg-you-might-be-an-investor
    - u-s-shaken-baby-syndrome-database